### ISSUE TITLE
adding a branch per iOS release (or sometimes)

### ISSUE THREAD

**Issue by DeveloppeurPascal** [FMXExpress/ios-object-pascal-wrapper#2]
Hi.
I've exported some iOS 16 frameworks and could share it too. 
Do you thing it could be a PULL REQUEST here with a iOS 16.x branch, on the master or not really useful ?

**Comment by FMXExpress** [comment]
Just put it in an IOS 16 directory and then the version here could move into a directory as well. That's how I have the Android side.
